[theme]
base="light"
primaryColor="#7fb3d5"                # blue accent (you can change this)
backgroundColor="#F4C095"             # your selected peach tone
secondaryBackgroundColor="f4f6f6"    # white cards
textColor="#000000"
font="sans serif"